'use strict';
/**
 * `lazytui build <config.yml>` — compile a lazytui app (the framework + its
 * config + any consumer Components) into ONE self-contained native binary with
 * `bun build --compile`. No Node/Bun needed to RUN the result.
 *
 * How it works (docs/packaging.md):
 *   1. Parse the YAML → the resolved config; pull out its `components:` list.
 *   2. Emit a tiny entry that statically `require`s lazytui's `run`, each
 *      Component, and the config (as embedded JSON), then calls
 *      `run({ config, components })`. STATIC requires are what Bun's bundler
 *      follows, so all three embed into the binary.
 *   3. `bun build <entry> --compile` → the binary.
 *
 * The one non-obvious rule: every generated `require(...)` uses a RELATIVE
 * specifier. Bun treats an ABSOLUTE-path require as *external* (won't bundle
 * it), so lazytui + the components must be reached relatively from the entry.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('child_process');

/** A relative, bun-bundleable specifier from `fromDir` to `toFile`. */
function relSpec(fromDir, toFile) {
  let r = path.relative(fromDir, toFile).split(path.sep).join('/');
  if (!r.startsWith('.')) r = './' + r;
  return r;
}

/**
 * The `require()` specifier for one component entry in the generated entry file.
 * A component is either an ABSOLUTE filesystem path (parse() resolved a
 * `.`-relative one) or a BARE package specifier (parse() leaves those as-is —
 * parser/index.js). relSpec only applies to the former; a bare name stays
 * verbatim so Bun resolves it through node_modules (relSpec would turn
 * `my-panel` into a bogus cwd-relative file path that won't bundle).
 */
function componentSpec(fromDir, c) {
  return path.isAbsolute(c) ? relSpec(fromDir, c) : c;
}

/**
 * Build a binary from a config file. Returns a process exit code.
 * opts: { out?: string, target?: string }
 */
function build(configPath, opts = {}) {
  const absConfig = path.resolve(configPath);
  if (!fs.existsSync(absConfig)) {
    console.error(`build: config not found: ${configPath}`);
    return 1;
  }

  // 1. Resolve the config + its component list (absolute paths, resolved by parse).
  let config;
  try {
    config = require('../parser').parse(absConfig);
  } catch (e) {
    console.error(`build: config: ${e.message}`);
    return 1;
  }
  const components = Array.isArray(config.components) ? config.components : [];
  // The Components are statically required in the entry (so they embed), so
  // strip them from the EMBEDDED config to avoid a runtime dynamic require of a
  // path that won't exist on the user's machine.
  const embedded = { ...config };
  delete embedded.components;

  // 2. Generate the entry + embedded config in a temp workdir.
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'lazytui-build-'));
  try {
    const cfgJson = path.join(work, 'config.json');
    fs.writeFileSync(cfgJson, JSON.stringify(embedded));

    const runSpec = relSpec(work, path.resolve(__dirname, 'tui.js'));
    const compLines = components.map(c => `    require(${JSON.stringify(componentSpec(work, c))})`).join(',\n');
    const entry = `'use strict';
// Generated by \`lazytui build\` — compiled with \`bun build --compile\`.
require(${JSON.stringify(runSpec)}).run({
  config: require('./config.json'),
  components: [
${compLines}
  ],
});
`;
    const entryPath = path.join(work, 'entry.js');
    fs.writeFileSync(entryPath, entry);

    // 3. Compile with bun.
    const out = path.resolve(opts.out || _defaultOut(absConfig));
    const bunArgs = ['build', entryPath, '--compile', '--outfile', out];
    if (opts.target) bunArgs.push('--target', opts.target);
    const res = spawnSync('bun', bunArgs, { stdio: 'inherit' });
    if (res.error && res.error.code === 'ENOENT') {
      console.error('build: `bun` was not found on PATH. Install Bun (https://bun.sh) — it is the build tool for compiled binaries (it is NOT needed to run the result).');
      return 127;
    }
    if (res.error) {   // bun found but could not be spawned (EACCES, etc.) — not a bun exit
      console.error(`build: could not run \`bun\`: ${res.error.message}`);
      return 126;
    }
    if (res.status !== 0) {
      console.error(`build: bun exited with ${res.status}`);
      return res.status || 1;
    }
    console.error(`build: wrote ${out}`);
    return 0;
  } finally {
    fs.rmSync(work, { recursive: true, force: true });
  }
}

/** Default output name: the config's basename minus extension (tui.yml → tui). */
function _defaultOut(absConfig) {
  const base = path.basename(absConfig).replace(/\.(ya?ml|json)$/i, '');
  return base || 'lazytui-app';
}

/** CLI: `build <config> [--out name] [--target t]`. Returns an exit code. */
function runCli(args) {
  let configPath = null;
  const opts = {};
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--out' || a === '-o') {
      if (i + 1 >= args.length) { console.error('build: --out requires a name'); return 2; }
      opts.out = args[++i];
    } else if (a === '--target') {
      if (i + 1 >= args.length) { console.error('build: --target requires a value (e.g. bun-linux-arm64)'); return 2; }
      opts.target = args[++i];
    } else if (a.startsWith('-')) {
      console.error(`build: unknown flag ${a}`);
      return 2;
    } else if (configPath === null) {
      configPath = a;
    } else {
      console.error(`build: unexpected extra argument '${a}' (one config at a time)`);
      return 2;
    }
  }
  if (!configPath) {
    console.error('Usage: lazytui build <config.yml> [--out <name>] [--target <bun-target>]');
    return 2;
  }
  return build(configPath, opts);
}

module.exports = { build, runCli, relSpec, componentSpec, _defaultOut };
